Repository eclipse-che/che-plugin-registry, pull requests merged in 2021-09, with the labels that each got.

#1022 chore: add pull-request check to ensure plugin sidecar has memory and CPU limitations
  .github/workflows/resource-limits-pr-check.yaml
  che-theia-plugins.yaml
  tools/automation/src/che-theia-plugins.ts
  tools/automation/src/check-plugin-updates.ts
  tools/automation/src/check-resource-limits.ts
  tools/automation/src/resource-limits-checker.ts
  tools/automation/tests/check-plugin-updates.spec.ts
  tools/automation/tests/check-resource-limits-checker.spec.ts
Labels: lgtm

#1039 feat: Add jsdebug VS Code Extension v1.52.2
  che-theia-plugins.yaml
Labels: lgtm

#1034 chore(yarn): Use newer Yarn3 stable release
  .yarn/releases/yarn-2.4.2.cjs
  .yarn/releases/yarn-3.0.1.cjs
  .yarnrc.yml
  yarn.lock
Labels: lgtm

#1045 fix: replace tag with digest in che-theia-plugin.yaml files
  build/dockerfiles/entrypoint.sh
  build/dockerfiles/test_entrypoint.sh
Labels: lgtm

#1000 feat: add jenkinsfile VS Code extension
  che-theia-plugins.yaml
Labels: lgtm, needs-ok-to-test

#1044 feat: adding 'try-in-web-ide' GitHub action
  .github/workflows/try-in-web-ide.yaml
Labels: lgtm

#1043 feat: Support CORS with credentials
  .htaccess
Labels: lgtm, ok-to-test

#1046 fix: apply urlRewriteSupported on stable version as well
  che-editors.yaml
Labels: lgtm

#1047 fix: apply urlRewriteSupported on stable version as well
  che-editors.yaml
Labels: lgtm

#1042 chore: Changed Zowe E4E version to 0.13.1
  che-theia-plugins.yaml
Labels: lgtm, ok-to-test

#1035 feat: Bump Ruby and Solargraph version
  che-theia-plugins.yaml
  sidecars/ruby/Dockerfile
Labels: lgtm, ok-to-test

#1048 chore(revert): Revert PR #1043
  .htaccess
Labels: lgtm

#1051 fix: don't rewrite 127 to 0.0.0.0
  tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts
  tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
Labels: lgtm

#1014 fix: CRW-2118: Contributing security updates for httpd
  build/dockerfiles/rhel.Dockerfile
Labels: lgtm, needs-ok-to-test

#1055 feat: Add volume mount to the runtime binary container
  che-editors.yaml
Labels: lgtm

#1056 feat: Add volume mount to the runtime binary container
  che-editors.yaml
Labels: lgtm

#1058 Filter identical volume mounts in components list
  tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts
  tools/build/tests/_data/meta/che-theia-meta-with-multiple-volumes.yaml
  tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
Labels: lgtm

#1059 Filter identical volume mounts in components list
  tools/build/src/devfile/meta-yaml-to-devfile-yaml.ts
  tools/build/tests/_data/meta/che-theia-meta-with-multiple-volumes.yaml
  tools/build/tests/devfile/meta-yaml-to-devfile-yaml.spec.ts
Labels: lgtm

#1057 feat: Add vscode-stylelint
  che-theia-plugins.yaml
Labels: lgtm, needs-ok-to-test

#1061 fix: update workflow to publish content from main
  .github/workflows/publish-content-push-main.yml
Labels: lgtm
